name: Build Windows wheels
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download Exiv2 source
        run: wget -nv https://github.com/Exiv2/exiv2/releases/download/v0.27.5/exiv2-0.27.5-Source.tar.gz

      - name: Store downloaded file
        uses: actions/upload-artifact@v3
        with:
          name: exiv2-source
          path: ./exiv2*.tar.gz
          retention-days: 1

  compile:
    needs: fetch
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Fetch Exiv2 source
        uses: actions/download-artifact@v3
        with:
          name: exiv2-source
          path: ./

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar xf exiv2-0.27.5-Source.tar.gz
          mv exiv2-0.27.5-Source exiv2-Source
          cp conanfile.py exiv2-Source/

      - name: Make directories
        working-directory: ./exiv2-Source
        run: |
          mkdir build
          mkdir local_install

      - name: Install dependencies
        working-directory: ./exiv2-Source/build
        run: |
          pip install --disable-pip-version-check wheel
          pip install --disable-pip-version-check conan
          conan install .. --build missing

      - name: Configure build
        working-directory: ./exiv2-Source/build
        run: >
          cmake .. -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=../local_install
          -DEXIV2_ENABLE_WIN_UNICODE=ON
          -DEXIV2_BUILD_SAMPLES=OFF
          -DEXIV2_BUILD_EXIV2_COMMAND=OFF
          -DEXIV2_ENABLE_BMFF=ON
          -DEXIV2_ENABLE_NLS=OFF
          -DCMAKE_CXX_STANDARD=98
          -G "Visual Studio 16 2019" -A x64

      - name: Compile Exiv2
        working-directory: ./exiv2-Source/build
        run: cmake --build . --config Release

      - name: Install Exiv2
        working-directory: ./exiv2-Source/build
        run: cmake --install . --config Release --prefix ../local_install

      - name: Store intermediate files
        uses: actions/upload-artifact@v3
        with:
          name: exiv2-windows
          path: ./exiv2-Source/local_install
          retention-days: 1

  wheels:
    needs: compile
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Fetch intermediate files
        uses: actions/download-artifact@v3
        with:
          name: exiv2-windows
          path: lib_exiv2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Build wheel
        run: |
          pip3 install --disable-pip-version-check setuptools wheel
          python3 utils/build_swig.py lib_exiv2/include
          pip wheel -v .
        env:
          EXIV2_ROOT: lib_exiv2

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheel
          path: ./*.whl

  test:
    needs: wheels
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: windows-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --disable-pip-version-check --no-index --find-links=. exiv2

      - name: Test installation
        run: python3 -m exiv2
