name: Build MacOS wheels (ARM)
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      EXIV2_ROOT: /Users/runner/exiv2-install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download libexiv2
        run: |
          wget -nv https://github.com/Exiv2/exiv2/releases/download/v0.27.6/exiv2-0.27.6-Source.tar.gz
          tar xf exiv2-0.27.6-Source.tar.gz

      - name: Make directories
        run: |
          mkdir exiv2-0.27.6-Source/build
          mkdir $EXIV2_ROOT

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS: arm64
          CIBW_SKIP: pp3?-*
          CIBW_BEFORE_ALL: >
            brew install ninja &&
            pip3 install conan==1.53.0 &&
            cd exiv2-0.27.6-Source/build &&
            conan profile new --detect default &&
            conan install .. -o unitTests=False -b missing -s arch=arm64 &&
            cmake .. -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ env.EXIV2_ROOT }} \
              -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
              -DEXIV2_BUILD_SAMPLES=OFF \
              -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
              -DEXIV2_ENABLE_BMFF=ON \
              -DEXIV2_ENABLE_NLS=ON \
              -DEXIV2_ENABLE_VIDEO=ON \
              -DCMAKE_CXX_STANDARD=98 \
              -DCMAKE_OSX_ARCHITECTURES=arm64 \
              -GNinja &&
            cmake --build . --config Release &&
            cmake --build . --target install &&
            cd ../.. &&
            python3 utils/build_swig.py ${{ env.EXIV2_ROOT }}/include

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheel
          path: wheelhouse/*.whl
