name: Build MacOS wheels
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      EXIV2_ROOT: /Users/runner/exiv2-install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download libexiv2
        run: |
          wget -nv https://github.com/Exiv2/exiv2/releases/download/v0.27.7/exiv2-0.27.7-Source.tar.gz
          tar xf exiv2-0.27.7-Source.tar.gz

      - name: Make directories
        run: |
          mkdir exiv2-0.27.7-Source/build
          mkdir $EXIV2_ROOT

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: x86_64
          CIBW_SKIP: pp3*
          CIBW_BEFORE_ALL: >
            brew install ninja &&
            pip3 install conan==1.59.0 "cython<3.0" &&
            cd exiv2-0.27.7-Source/build &&
            conan profile new --detect default &&
            conan install .. -o unitTests=False -b missing &&
            cmake .. -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ env.EXIV2_ROOT }} \
              -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
              -DEXIV2_BUILD_SAMPLES=OFF \
              -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
              -DEXIV2_ENABLE_BMFF=ON \
              -DEXIV2_ENABLE_NLS=ON \
              -DEXIV2_ENABLE_VIDEO=ON \
              -DCMAKE_CXX_STANDARD=98 \
              -GNinja &&
            cmake --build . --config Release &&
            cmake --build . --target install &&
            cd ../.. &&
            python3 utils/build_swig.py ${{ env.EXIV2_ROOT }}/include

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheel
          path: wheelhouse/*.whl

  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: macos-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --disable-pip-version-check --no-index --find-links=. exiv2

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get package details
        run: python3 -m exiv2

      - name: Run unit tests
        run: python3 -m unittest discover tests
