name: Test build Windows exiv2
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download Exiv2 source
        run: wget -nv https://www.exiv2.org/builds/exiv2-0.27.4-Source.tar.gz

      - name: Store downloaded files
        uses: actions/upload-artifact@v2
        with:
          name: exiv2-source
          path: ./exiv2*.tar.gz
          retention-days: 1

  build:
    needs: fetch
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: vcpkg install zlib libiconv expat --triplet=x64-windows

      - name: Fetch Exiv2 source
        uses: actions/download-artifact@v2
        with:
          name: exiv2-source
          path: ./

      - name: Extract Exiv2 source
        shell: bash
        run: tar xf exiv2-0.27.4-Source.tar.gz

      - name: Make directories
        working-directory: ./exiv2-0.27.4-Source
        run: |
          mkdir build
          mkdir local_install

      - name: Configure build
        working-directory: ./exiv2-0.27.4-Source/build
        env:
          CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        run: cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=../local_install \
                -DEXIV2_ENABLE_WIN_UNICODE=ON \
                -DEXIV2_BUILD_SAMPLES=OFF \
                -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
                -G "Visual Studio 16 2019" -A x64

      - name: Compile Exiv2
        working-directory: ./exiv2-0.27.4-Source/build
        run: cmake --build . --config Release

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: windows-exiv2
          path: ./exiv2-0.27.4-Source/local_install
